package com.zh.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.app.tvproject.mvp.model.data.ContentBean;
import com.app.tvproject.mvp.model.data.TestBean;

import com.zh.greendao.ContentBeanDao;
import com.zh.greendao.TestBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contentBeanDaoConfig;
    private final DaoConfig testBeanDaoConfig;

    private final ContentBeanDao contentBeanDao;
    private final TestBeanDao testBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contentBeanDaoConfig = daoConfigMap.get(ContentBeanDao.class).clone();
        contentBeanDaoConfig.initIdentityScope(type);

        testBeanDaoConfig = daoConfigMap.get(TestBeanDao.class).clone();
        testBeanDaoConfig.initIdentityScope(type);

        contentBeanDao = new ContentBeanDao(contentBeanDaoConfig, this);
        testBeanDao = new TestBeanDao(testBeanDaoConfig, this);

        registerDao(ContentBean.class, contentBeanDao);
        registerDao(TestBean.class, testBeanDao);
    }
    
    public void clear() {
        contentBeanDaoConfig.clearIdentityScope();
        testBeanDaoConfig.clearIdentityScope();
    }

    public ContentBeanDao getContentBeanDao() {
        return contentBeanDao;
    }

    public TestBeanDao getTestBeanDao() {
        return testBeanDao;
    }

}
